operator: NUFFT_SPIDER
network: GUNet
dataset: COCO
ISNR: 30
exp_name: test

data_base_folder: "./data/"
checkpoint_base_folder: "./models/"
log_base_folder: "./logs/"
results_base_folder: "./results/"

Nd: 256 # input image size
Kd: 512 # upsampled image size (for use in NUFFT operator)
Jd: 6   # NUFFT kernel size 

epochs: 200
batch_size: 20
save_freq: 5

train_size: 2000
val_size: 1000
test_size: 1000
save_freq: 5